### ISSUE TITLE
Разобраться, как хранит данные OSM

### ISSUE THREAD

**Issue by mirrin00** [moevm/nosql2h22-bottle-neck#8]

**Comment by mirrin00** [comment]
Дедлайн 19 октября (среда), 23:59

**Comment by IlyaTsaplin** [comment]
Три компонента данных:
- Узлы (Nodes) - точки в пространстве, имеют атрибуты ширины, долготы, идентификатора и т.п.
- Пути (Ways) - набор от 2 до 2000 узлов, отражают дороги, контуры зданий
- Отношения (Relations) - структура данных, которая отражает отношение между двумя и более структурами данных (между узлами, путями и/или другими отношениями)

Примеры отношений: 
- объединение путей в многокилометровую магистраль (более 2000 узлов)
- маршрут автобуса
- запрет движения из одного пути в другой путь

Все типы данных могут иметь внутренние теги (Tags). Теги описывают значение элемента, частью которого они являются. Тег состоит из двух полей ключ и значение.
Например, тег \<tag k = highway, v = residential\> в элементе типа путь (way) сообщает о том, что данный путь - дорога в жилой застройке 

[Источник](https://wiki.openstreetmap.org/wiki/Elements)
